### ISSUE TITLE
All my options are being ignored

### ISSUE THREAD

**Issue by pzi** [dtaniwaki/rack-dev-mark#24]
Hey,

I added the gem, then ran my rails app in development and it was showing the ribbon with the text 'staging'.

I disabled the mark with `config.rack_dev_mark.enable = false` in app.rb, dev.rb and it was still showing the ribbon with 'staging' as text.

It seems that this check here actually is not working properly as by default it's always shown anyway:
https://github.com/dtaniwaki/rack-dev-mark/blob/master/lib/rack/dev-mark/railtie.rb#L28

**Comment by dtaniwaki** [comment]
Do you have `RACK_DEV_MARK_ENV` in the env?

**Comment by dtaniwaki** [comment]
And you need to put `config.rack_dev_mark.enable = true/false` in `application.rb`.

**Comment by pzi** [comment]
It seems to work now, I think it was some weird caching issue. I removed everything and then added just these 2 lines to my `application.rb`:

```ruby
config.rack_dev_mark.enable = Rails.env.staging?
config.rack_dev_mark.theme = [:title, Rack::DevMark::Theme::GithubForkRibbon.new(position: 'right')]
```

This seems to do the job properly.

**Comment by pzi** [comment]
Actually no... it still doesn't work as expected:

In `application.rb`:
```ruby
config.rack_dev_mark.enable = false
```

In `staging.rb`:
```ruby
config.rack_dev_mark.enable = true
config.rack_dev_mark.theme = [:title, Rack::DevMark::Theme::GithubForkRibbon.new(position: 'right')]
```

Now it shows the ribbon in development with the word `staging`.

**Comment by dtaniwaki** [comment]
Please tell me if you still have the issue. You can provide me your `config/environements/development.rb` and the result of `env` for the further investigation.
