### ISSUE TITLE
Do you plan to release removed before_filter version?

### ISSUE THREAD

**Issue by eccyan** [dtaniwaki/rack-dev-mark#43]
Hi :)
I use rack-dev-mark 0.7.5. I want use version containing this commit https://github.com/dtaniwaki/rack-dev-mark/commit/da27ec971d1147cc409e28bb5e7e80a6f76c76d5 .
I wirte Gemfile ref to master, now. Are you planning to update gem?

**Comment by dtaniwaki** [comment]
Sorry for the late reply. I will release new version in a few days.

**Comment by eccyan** [comment]
@dtaniwaki Awesome! Thank you for reply 😄

**Comment by dtaniwaki** [comment]
@eccyan I have released [0.7.6](https://rubygems.org/gems/rack-dev-mark/versions/0.7.6). Thank you for using my gem. :)

**Comment by eccyan** [comment]
Thank you for updating :)
