### ISSUE TITLE
Remove/Replace Rack::Utils::HeaderHash

### ISSUE THREAD

**Issue by nari** [dtaniwaki/rack-dev-mark#67]
Happened warning log: `warning: Rack::Utils::HeaderHash is deprecated and will be removed in Rack 3.1, switch to Rack::Headers` 
in the [rack-dev-mark-0.7.11/lib/rack/dev-mark/middleware.rb:21](https://github.com/dtaniwaki/rack-dev-mark/blob/master/lib/rack/dev-mark/middleware.rb#L21C42-L21C42) when I update `rails 7.1.0` 

The Rack::Utils::HeaderHash was removed by Rack on the commit:
https://github.com/rack/rack/commit/a5762cf60af474b89b555ff8d151be5a021701f8#diff-85960cbd609e7f51a9881d1876b82d748f4ba8312a31e3329a5bb9bf791c60be

**Comment by mishina2228** [comment]
#68 has been merged so this can be closed.

**Comment by dtaniwaki** [comment]
Thank you!
